### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/NewSite#5]
I recommend adding a license file even if it is "Libretexts retains copyright."

**Comment by Miniland1333** [comment]
Besides the LibreText logos/trademarks that are used, I don't have any specific reservations for this repository.

Do you have a recommendation for a license that respects the original CC BY 3.0 license that this was based off of?

**Comment by moorepants** [comment]
If it was CC-BY 3.0 then it is easiest to use CC-BY 3.0 here.

**Comment by Miniland1333** [comment]
Closed using CC-BY-4.0 license. Also included changes to differentiate between Template's license versus LibreText's trademarks verus LibreText content.
